server:
   port: 8080
   servlet:
     context-path: /
     encoding:
       force: true
       charset: UTF-8
       enabled: true
   tomcat:
     uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: lixin123
    url: jdbc:mysql://localhost:3306/car_timetable?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
#server.tomcat.uri-encoding=UTF-8

logging:
  root:
    level: debug